#!/bin/bash
set -eo pipefail
IFS=$'\n\t'

sandbox () {
      if [ "$2" == "-nightly" ]; then
        source .env-nightlies
        echo "Using nightlies...removing old ones."        
        # If nightly images already exist, containers are stopped, destroyed,
        # and rebuilt using newly pulled images
        if [ $(docker images | grep nightly | tr -s ' ' | cut -d ' ' -f 3 | wc -l) -gt 0 ]; then
          docker-compose down
          docker-compose rm -f
          docker-compose build --pull
        fi
      else
        source .env-latest
        echo "Using latest, stable releases"
      fi
  # Enter attaches users to a shell in the desired container
  enter () {
    case $2 in
      influxdb | chronograf | kapacitor | telegraf | flux | grafana)
        echo "Entering /bin/bash session in the $2 container..."
        docker-compose exec $2 /bin/bash
        ;;
      *)
        echo "sandbox enter (influxdb||chronograf||kapacitor||telegraf||flux||grafana)"
        ;;
    esac
  }

  # Logs streams the logs from the container to the shell
  logs () {
    case $2 in
      influxdb | chronograf | kapacitor | telegraf | grafana)
        echo "Following the logs from the $2 container..."
        docker-compose logs $3 $2
        ;;
      *)
        echo "sandbox logs (influxdb||chronograf||kapacitor||telegraf)"
        ;;
    esac
  }

  case $1 in
    up)
      echo "Spinning up Docker Images..."
      echo "If this is your first time starting sandbox this might take a minute..."
      docker-compose up -d --build
      echo "Opening tabs in browser..."
      sleep 3
      if [ $(uname) == "Darwin" ]; then
        open http://localhost:3010
        open http://localhost:8888
        open http://localhost:3000
      elif [ $(uname) == "Linux" ]; then
        sensible-browser http://localhost:8888
        sensible-browser http://localhost:3010
        sensible-browser http://localhost:3000
      else
        echo "no browser detected..."
      fi
      ;;
    down)
      echo "Stopping sandbox containers..."
      docker-compose down
      ;;
    restart)
      echo "Stopping all sandbox processes..."
      docker-compose down > /dev/null 2>&1
      echo "Starting all sandbox processes..."
      docker-compose up -d --build > /dev/null 2>&1
      echo "Services available!"
      ;;
    delete-data)
      echo "deleting all influxdb, kapacitor and chronograf data..."
      rm -rf kapacitor/data influxdb/data chronograf/data
      ;;
    docker-clean)
      echo "Stopping and removing running sandbox containers..."
      docker-compose down
      echo "Removing TICK images..."
      docker rmi sandbox_documentation influxdb:latest telegraf:latest kapacitor:latest chronograf:latest chrono_config:latest quay.io/influxdb/influxdb:nightly quay.io/influxdb/chronograf:nightly> /dev/null 2>&1
      docker rmi $(docker images -f "dangling=true" -q)
      ;;
    influxdb)
      echo "Entering the influx cli..."
      docker-compose exec influxdb /usr/bin/influx
      ;;
    rebuild-docs)
      echo "Rebuilding documentation container..."
      docker build -t sandbox_documentation documentation/ > /dev/null 2>&1
      echo "Restarting..."
      docker-compose down > /dev/null 2>&1
      docker-compose up -d --build > /dev/null 2>&1
      ;;
    enter)
      enter $@
      ;;
    logs)
      logs $@
      ;;
    *)
      cat <<-EOF
sandbox commands:
  up (-nightly)      -> spin up the sandbox environment (latest or nightlies specified in the companion file)
  down               -> tear down the sandbox environment (latest or nightlies specified in the companion file)
  restart (-nightly) -> restart the sandbox
  influxdb           -> attach to the influx cli

  enter (influxdb||kapacitor||chronograf||telegraf|flux|grafana) -> enter the specified container
  logs  (influxdb||kapacitor||chronograf||telegraf|grafana) [-f] -> stream logs for the specified container

  delete-data  -> delete all data created by the TICK Stack
  docker-clean -> stop and remove all running docker containers and images
  rebuild-docs -> rebuild the documentation image
EOF
      ;;
  esac
}

sandbox $@
